import json
import os
from pathlib import Path
from typing import Any, Literal

import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, ConfigDict


class AgentDecision(BaseModel):
    """Only the final decision generated by the language model."""

    model_config = ConfigDict(extra="forbid")

    action: Literal["reply_to_client", "escalate_to_human"]
    decision_reason: str
    response_email: str | None
    human_note: str | None


SYSTEM_PROMPT = """
You are a Case Management Agent for an insurance company.

You receive a classified customer email and can consult internal policy and
claim records through tools. Your final task is deliberately simple: choose
exactly one of these actions:

1. reply_to_client
2. escalate_to_human

Rules for reply_to_client:
- Use this action only when the available information is sufficient and safe.
- Write a complete, professional and helpful email in response_email.
- Base every policy or claim fact on the results returned by the tools.
- Set human_note to null.

Rules for escalate_to_human:
- Use this action for complaints, contested decisions, sensitive cases,
  low-confidence classifications, missing identifiers that are necessary,
  records that are not found, inconsistent information, or any request that
  cannot be answered safely and completely.
- Set response_email to null.
- Write a concise and useful note in human_note explaining what the human
  operator should verify or do next.

General rules:
- Never invent internal policy or claim information.
- Never say that a record exists unless a tool found it.
- Use get_policy when policy information is necessary and a policy number is
  available.
- Use get_claim when claim information is necessary and a claim number is
  available.
- Never approve or reject a claim.
- Never promise payments or reimbursements.
- Never modify policies or claims.
- Do not mention internal tools or automated processing in the customer email.
- decision_reason is an internal, concise explanation of the selected action.
""".strip()


TOOL_DEFINITIONS = [
    {
        "type": "function",
        "name": "get_policy",
        "description": "Retrieve a policy record from the internal database.",
        "parameters": {
            "type": "object",
            "properties": {
                "policy_number": {
                    "type": "string",
                    "description": "The exact policy number from the classified email.",
                }
            },
            "required": ["policy_number"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_claim",
        "description": "Retrieve a claim record from the internal database.",
        "parameters": {
            "type": "object",
            "properties": {
                "claim_number": {
                    "type": "string",
                    "description": "The exact claim number from the classified email.",
                }
            },
            "required": ["claim_number"],
            "additionalProperties": False,
        },
        "strict": True,
    },
]


CLASSIFIED_EMAIL_COLUMNS = {
    "id",
    "subject",
    "body",
    "insurance_type",
    "intent",
    "priority",
    "policy_number",
    "claim_number",
    "requires_human_review",
    "confidence",
}

INTERNAL_RECORD_COLUMNS = {
    "code",
    "record_type",
    "insurance_type",
    "status",
    "details",
}

OUTPUT_COLUMNS = [
    "email_id",
    "subject",
    "body",
    "insurance_type",
    "intent",
    "priority",
    "policy_number",
    "claim_number",
    "action",
    "decision_reason",
    "response_email",
    "human_note",
]


def load_csv(path: Path, required_columns: set[str]) -> pd.DataFrame:
    """Load a CSV and verify that all required columns are present."""

    if not path.exists():
        raise FileNotFoundError(f"Input dataset not found: {path}")

    dataframe = pd.read_csv(path, dtype=str, keep_default_na=False)
    missing_columns = required_columns - set(dataframe.columns)

    if missing_columns:
        raise ValueError(
            f"The dataset {path} is missing columns: {sorted(missing_columns)}"
        )

    return dataframe


def clean_value(value: Any) -> str | None:
    """Return a clean string, or None for an empty value."""

    if value is None or pd.isna(value):
        return None

    cleaned = str(value).strip()
    return cleaned or None


def get_internal_record(
    code: str,
    record_type: Literal["policy", "claim"],
    internal_records: pd.DataFrame,
) -> dict[str, Any]:
    """Retrieve exactly one policy or claim record."""

    normalized_code = code.strip()

    mask = (
        internal_records["code"].str.strip().eq(normalized_code)
        & internal_records["record_type"].str.strip().str.lower().eq(record_type)
    )
    matching_records = internal_records.loc[mask]

    if matching_records.empty:
        return {
            "found": False,
            "code": normalized_code,
            "record_type": record_type,
            "message": f"{record_type.capitalize()} not found.",
        }

    if len(matching_records) > 1:
        return {
            "found": False,
            "code": normalized_code,
            "record_type": record_type,
            "message": (
                f"Multiple {record_type} records were found for this identifier. "
                "Human verification is required."
            ),
        }

    record = matching_records.iloc[0]

    return {
        "found": True,
        "code": clean_value(record["code"]),
        "record_type": clean_value(record["record_type"]),
        "insurance_type": clean_value(record["insurance_type"]),
        "status": clean_value(record["status"]),
        "details": clean_value(record["details"]),
    }


def execute_tool(
    tool_name: str,
    arguments: dict[str, Any],
    internal_records: pd.DataFrame,
) -> dict[str, Any]:
    """Execute one internal-record tool selected by the model."""

    if tool_name == "get_policy":
        policy_number = arguments.get("policy_number")
        if not isinstance(policy_number, str) or not policy_number.strip():
            raise ValueError("get_policy requires a non-empty policy_number.")

        return get_internal_record(
            code=policy_number,
            record_type="policy",
            internal_records=internal_records,
        )

    if tool_name == "get_claim":
        claim_number = arguments.get("claim_number")
        if not isinstance(claim_number, str) or not claim_number.strip():
            raise ValueError("get_claim requires a non-empty claim_number.")

        return get_internal_record(
            code=claim_number,
            record_type="claim",
            internal_records=internal_records,
        )

    raise ValueError(f"Unknown tool requested: {tool_name}")


def build_agent_input(
    email: pd.Series,
) -> list[dict[str, str]]:
    """Build the initial model input for one classified email."""

    user_prompt = """
Process the following classified insurance email:

Email ID: {id}
Subject: {subject}
Body: {body}
Insurance type: {insurance_type}
Intent: {intent}
Priority: {priority}
Policy number: {policy_number}
Claim number: {claim_number}
Requires human review: {requires_human_review}
Classification confidence: {confidence}
""".strip().format(**email)

    return [
        {
            "role": "system",
            "content": SYSTEM_PROMPT,
        },
        {
            "role": "user",
            "content": user_prompt,
        },
    ]


def run_case_management_agent(
    client: OpenAI,
    model: str,
    email: pd.Series,
    internal_records: pd.DataFrame,
    max_iterations: int = 5,
) -> AgentDecision:
    """Run the agent until it returns a reply or a human escalation."""

    model_input = build_agent_input(email)

    for _ in range(max_iterations):
        response = client.responses.parse(
            model=model,
            input=model_input,
            tools=TOOL_DEFINITIONS,
            text_format=AgentDecision,
        )

        model_input.extend(response.output)

        tool_calls = [
            item for item in response.output if item.type == "function_call"
        ]

        if not tool_calls:
            decision = response.output_parsed

            if decision is None:
                raise RuntimeError("The model did not return a valid decision.")

            return decision

        for tool_call in tool_calls:
            try:
                arguments = json.loads(tool_call.arguments)
                tool_name = tool_call.name
                tool_result = execute_tool(
                    tool_name=tool_name,
                    arguments=arguments,
                    internal_records=internal_records,
                )
            except Exception as error:
                tool_result = {
                    "found": False,
                    "message": f"Tool execution failed: {error}",
                }

            model_input.append(
                {
                    "type": "function_call_output",
                    "call_id": tool_call.call_id,
                    "output": json.dumps(tool_result, ensure_ascii=False),
                }
            )

    return AgentDecision(
        action="escalate_to_human",
        decision_reason="The agent reached the maximum number of iterations.",
        response_email=None,
        human_note=(
            "Review the request manually because the automated process could "
            "not reach a final decision within the allowed iterations."
        ),
    )


def build_output_row(
    email: pd.Series,
    decision: AgentDecision,
) -> dict[str, Any]:
    """Combine the original request with the final management decision."""

    output_row = email.to_dict()

    output_row["email_id"] = output_row.pop("id")
    output_row.update(decision.model_dump())

    return output_row

def process_emails(
    client: OpenAI,
    model: str,
    classified_emails: pd.DataFrame,
    internal_records: pd.DataFrame,
    number_of_emails: int | None = None,
) -> pd.DataFrame:
    """Process a batch and return one output row for every selected email."""

    if number_of_emails is not None and number_of_emails <= 0:
        raise ValueError("number_of_emails must be greater than zero or None.")

    emails_to_process = (
        classified_emails
        if number_of_emails is None
        else classified_emails.head(number_of_emails)
    )

    rows: list[dict[str, Any]] = []

    for _, email in emails_to_process.iterrows():
        email_id = clean_value(email.get("id")) or "unknown-email"
        print(f"Processing email {email_id}...")

        try:
            decision = run_case_management_agent(
                client=client,
                model=model,
                email=email,
                internal_records=internal_records,
            )
        except Exception as error:
            # The batch continues, but the output explicitly tells the human
            # operator that this was a technical failure rather than a business
            # decision made by the model.
            decision = AgentDecision(
                action="escalate_to_human",
                decision_reason="The automated process encountered an error.",
                response_email=None,
                human_note=(
                    "Review this request manually. The automated process failed "
                    f"with the following technical error: {error}"
                ),
            )
            print(f"Email {email_id} sent to human review: {error}")

        rows.append(build_output_row(email, decision))

    return pd.DataFrame(rows, columns=OUTPUT_COLUMNS)


def save_case_decisions(
    decisions: pd.DataFrame,
    output_path: Path,
) -> None:
    """Save the case-management dataset to CSV."""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    decisions.to_csv(output_path, index=False)





def main() -> None:
    load_dotenv()

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY was not found. Check the .env file.")

    client = OpenAI(api_key=api_key)
    model = os.getenv("OPENAI_MODEL", "gpt-5.4-mini")
    number_of_emails = 150

    classified_emails_path = Path("data/classified_emails.csv")
    internal_records_path = Path("data/internal_records.csv")
    output_path = Path("data/case_decisions.csv")

    classified_emails = load_csv(
        classified_emails_path,
        CLASSIFIED_EMAIL_COLUMNS,
    )
    internal_records = load_csv(
        internal_records_path,
        INTERNAL_RECORD_COLUMNS,
    )

    if number_of_emails is None:
        print(f"Processing all {len(classified_emails)} emails with {model}...")
    else:
        print(f"Processing up to {number_of_emails} emails with {model}...")

    decisions = process_emails(
        client=client,
        model=model,
        classified_emails=classified_emails,
        internal_records=internal_records,
        number_of_emails=number_of_emails,
    )
    save_case_decisions(decisions, output_path)

    reply_count = int((decisions["action"] == "reply_to_client").sum())
    escalation_count = int((decisions["action"] == "escalate_to_human").sum())

    print()
    print(f"Rows generated: {len(decisions)}")
    print(f"Replies generated: {reply_count}")
    print(f"Human escalations: {escalation_count}")
    print(f"Results saved to: {output_path}")


if __name__ == "__main__":
    main()
